# env
env: "local"
# http(address, timeout, idle timeout
server:
  address: "localhost:8080"
#  timeout: 5s
#  idle_timeout: 60s

#logger
logger:
  level: debug
# postgres
postgres:
#  POSTGRES_HOST: localhost
#  POSTGRES_PORT: 5432
#  POSTGRES_USER: user
#  POSTGRES_PASSWORD: password
#  POSTGRES_DB: dbname
  max_idle_connections: 10
  max_open_connections: 5
  conn_max_lifetime: 60
#  port: 5432
# storage path?(не надо так как мы в postgre, хотя может и оможно)

analytics:
  # What to include in analytics
  include:
    days: true
    months: true
    user_agent: true
    recent_accesses: true

  # Limits for each type
  limits:
    recent_accesses: 10
    days: 30
    months: 12
    user_agents: 20
